name: Generate Contribution Car

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate contribution car
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ramanvhantale
        run: |
          node scripts/generate-car-contribution.cjs

      - name: Commit contribution animation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/contribution-car.svg

          git diff --cached --quiet || git commit \
            -m "Update contribution car animation"

          git push
